server:
  port: 9071

spring:
  datasource:
    url: ${DEV_URL:jdbc:mysql://appuntesdbid.cqgwu6kfqjnq.us-east-1.rds.amazonaws.com:3306/}
    username: dev-sales
    password: dev-sales2023
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"